import type { Metadata } from "next";
import Navbar from "../components/layout/Navbar";
import Footer from "../components/layout/Footer";
import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import { siteConfig } from "@/config/site";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-montserrat",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable}`}>
      <body 
        className="antialiased min-h-screen flex flex-col overflow-x-hidden"
        style={
          {
            "--bg-primary": siteConfig.branding.colors.background.primary,
            "--bg-secondary": siteConfig.branding.colors.background.secondary,
            "--text-primary": siteConfig.branding.colors.text.primary,
            "--text-inverse": siteConfig.branding.colors.text.inverse,
            "--accent-primary": siteConfig.branding.colors.accent.primary,
            "--accent-hover": siteConfig.branding.colors.accent.hover,
            "--border": siteConfig.branding.colors.border,
          } as React.CSSProperties
        } 
      >
        <Navbar />
        <main className="flex-1">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
